title: "Alex Dong's Blog"
email: me@alexdong.com
description: "Stream of thoughts from Alex Dong. What I find interesting, intriguing or insightful."
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://alexdong.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: alexdong
github_username:  alexdong

theme: minima
plugins:
  - jekyll-feed

# Permalink configuration for shorter URLs
permalink: /:title.html

# Sass configuration to suppress deprecation warnings
sass:
  quiet_deps: true
  verbose: false
